name: Build & Deploy Recipe App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component:
          - api
          - ui
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"
          cache: npm
          cache-dependency-path: "**/package-lock.json"
      - name: "run ${{matrix.component}} unit tests"
        working-directory: "./${{matrix.component}}"
        run: |
          npm ci
          npm run test
  build-and-deploy:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"
          cache: npm
          cache-dependency-path: "**/package-lock.json"
      - name: Configure AWS Credentials
        id: aws_credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Setup Open Tofu
        uses: opentofu/setup-opentofu@v1
      - name: Provision recipe lambda & website
        working-directory: "./infra"
        run: |
          tofu init --backend-config="bucket=${{vars.AWS_TERRAFORM_STATE_BUCKET_NAME}}" --backend-config="key=${{vars.AWS_TERRAFORM_STATE_KEY}}.tfstate"
          tofu apply -auto-approve
        env:
          TF_VAR_aws_access_key: "${{secrets.AWS_ACCESS_KEY_ID}}"
          TF_VAR_aws_secret_key: "${{secrets.AWS_SECRET_ACCESS_KEY}}"
  e2e-tests:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"
          cache-dependency-path: "**/package-lock.json"
      - name: Configure AWS Credentials
        id: aws_credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Get outputs
        uses: dflook/tofu-output@v1
        id: tf-outputs
        with:
          path: ./infra
          backend_config: bucket=${{ vars.AWS_TERRAFORM_STATE_BUCKET_NAME }} key=${{ vars.AWS_TERRAFORM_STATE_KEY }}.tfstate
      - name: Prepare run Cypress
        working-directory: ./e2e
        run: npm ci
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: ./e2e
          config: >-
            baseUrl=https://${{ steps.tf-outputs.outputs.website_url }}
          spec: cypress/e2e/recipe_app.cy.ts
